config/routes.rb
Rails.application.routes.draw do
  	get 'players/new'
  	get '/teams', to: 'application#hello', as: 'team'
  	resources :players
	root 'cgame#index'
	#root 'application#hello' 
	get '/stats', to: 'cgame#index', as: 'stats'
	get '/other', to: 'cgame#other', as: 'other'
	get '/sort', to: 'cgame#sort', as: 'sort'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cgame.rb
class Cgame < ApplicationRecord
  belongs_to :player
  belongs_to :home_team, :class_name => "Team"
  belongs_to :away_team, :class_name => "Team"
  
  def self.getCurrentStats(categories)
    result=ActiveRecord::Base.connection.execute("SELECT #{categories} FROM (SELECT ROW_NUMBER() OVER (PARTITION BY name ORDER BY games_played DESC) as r, cgames.* FROM cgames ) x WHERE x.r =1").values  
  end

  def self.getNGamesAgoStats(categories, n)
    result=ActiveRecord::Base.connection.execute("SELECT #{categories} FROM (SELECT ROW_NUMBER() OVER (PARTITION BY name ORDER BY games_played DESC) as r, cgames.* FROM cgames ) x WHERE x.r =#{n+1}").values  
  end

  def self.currentMinusNgames(current, ngamesago, numgames)
    current = current.slice(3,current.length-3)
    ngamesago = ngamesago.slice(3, ngamesago.length-3)
    stats=[]
    current.length.times do |i|
        stats<<current[i]-ngamesago[i]
    end
    stats
  end

  def self.reinsertNamesGames(stats, original, numGames) 
  	stats.zip(original.map{|player| [player[0],[player[2]+1,numGames].min, player[1]]}).map{|statLine, name_games, player_id| statLine.unshift(name_games[0],name_games[1]).push(player_id)}
  end

  def self.getRatings(statLines, min, max, weights)
  	statLines = statLines.map{|playerStats| playerStats.zip(min,max,weights)}.map{|row|row.map{|stat,minStat,maxStat,weight| (stat.to_f-minStat)/(maxStat-minStat)*weight}}
  	ratings = statLines.map{|playerStatLine| playerStatLine.sum}
  	ratings
  end

  def self.getLastNGamesStatLines(currentStatLines, oldStatLines, numGames)
  	lastNGamesStatLines = []

  	currentStatLines.zip(oldStatLines).map do |current, old|
  		lastNGamesStatLines.push(currentMinusNgames(current, old, numGames))
  	end
  	lastNGamesStatLines
  end

  def self.getTotalAdjusted(categories, numGames, weights)
  	currentStatLines = getCurrentStats(categories)
  	oldStatLines = getNGamesAgoStats(categories, numgames)

  	lastNGamesStatLines = getLastNGamesStatLines(currentStatLines, oldStatLines, numGames)
  	min = lastNGamesStatLines.transpose.map{|column| column.min}
  	max = lastNGamesStatLines.transpose.map{|column| column.max}
  	adjustedStatLines = lastNGamesStatLines.map{|playerStats| playerStats.zip(min,max)}.map{|row|row.map{|stat,minStat,maxStat| (stat.to_f-minStat)/(maxStat-minStat)}}
  	adjustedStatLines = adjustedStatLines.map{|playerStatLine| playerStatLine.push(playerStatLine.sum)}
  	adjustedStatLines = reinsertNamesGames(adjustedStatLines, currentStatLines, numGames)
  	adjustedStatLines.sort_by!{|statLine| -statLine[statLine.length-2]}
  end

  def self.getMin(lastNGamesStatLines, games_played)
  	min=[10000]*lastNGamesStatLines[0].length
  	games_played.length.times do |i|
  		if games_played[i]>5
  			lastNGamesStatLines[0].length.times.each do |j|
  				min[j]>lastNGamesStatLines[i][j] ? min[j] = lastNGamesStatLines[i][j] : min[j]
  			end
  		end
  	end
  	min
  end

  def self.getMax(lastNGamesStatLines, games_played)
  	max=[-10000]*lastNGamesStatLines[0].length
  	games_played.length.times.each do |i|
  		if games_played[i]>5
  			lastNGamesStatLines[0].length.times.each do |j|
  				max[j]<lastNGamesStatLines[i][j] ? max[j] = lastNGamesStatLines[i][j] : max[j]
  			end
  		end
  	end
  	max
  end

  def self.fillOutOldStats(currentStatLines, incompleteOldStatLines)
    incompleteOldStatLines = nil ? num_old=0 : num_old=incompleteOldStatLines.length
    completeOldStatLines=[]
    num_missing=0
    currentStatLines.length.times do |i|
      if i>num_old or currentStatLines[i][1]!=incompleteOldStatLines[i-num_missing][1]
        completeOldStatLines<<currentStatLines[i].slice(0,2)+[0]*(currentStatLines[i].length-2)
        num_missing+=1
      else
        completeOldStatLines<<incompleteOldStatLines[i-num_missing]
      end
    end
    completeOldStatLines
  end

  def self.getTotal(categories, numGames, weights)
  	currentStatLines = getCurrentStats(categories)
  	incompleteOldStatLines = getNGamesAgoStats(categories, numGames)

    oldStatLines = fillOutOldStats(currentStatLines, incompleteOldStatLines)
  	lastNGamesStatLines = getLastNGamesStatLines(currentStatLines, oldStatLines, numGames)

  	games_played = currentStatLines.map{|player| [player[2]+1,numGames].min}
  	min = getMin(lastNGamesStatLines, games_played)
  	max = getMax(lastNGamesStatLines, games_played)

  	ratings=getRatings(lastNGamesStatLines, min, max, weights)
  	lastNGamesStatLines.zip(ratings).map{|statLine, rating| statLine.push(rating)}

  	lastNGamesStatLines=reinsertNamesGames(lastNGamesStatLines, currentStatLines, numGames)
  	lastNGamesStatLines.sort_by!{|statLine| -statLine[statLine.length-2]}

  end

  def self.getAverage(categories,numGames, weights)
  	currentStatLines = getCurrentStats(categories)
  	#oldStatLines = getNGamesAgoStats(categories, numGames)
  	games_played = currentStatLines.map{|player| [player[:games_played]+1,numGames].min}
  	#lastNGamesStatLines = getLastNGamesStatLines(currentStatLines, oldStatLines, numGames)
  	lastNGamesStatLines=currentStatLines
  	lastNGamesStatLines=lastNGamesStatLines.zip(games_played).map{|statLine,games| statLine.map{|stat| (stat.to_f*81/games)}}
  	min = lastNGamesStatLines.transpose.map{|column| column.min}
  	max = lastNGamesStatLines.transpose.map{|column| column.max}
  	min = getMin(lastNGamesStatLines, games_played)
  	max = getMax(lastNGamesStatLines, games_played)
  	ratings=getRatings(lastNGamesStatLines, min, max, weights)
  	lastNGamesStatLines.map!{|player| player.map{|stat| stat.round(0)}}
  	lastNGamesStatLines.zip(ratings).map{|statLine, rating| statLine.push(rating)}
  	lastNGamesStatLines=reinsertNamesGames(lastNGamesStatLines, currentStatLines, numGames)
  	lastNGamesStatLines.sort_by!{|statLine| -statLine[statLine.length-2]}
  end

  def self.getAverageAdjusted(categories, numgames, weights)
  	currentStatLines = getCurrentStats(categories)
  	oldStatLines = getNGamesAgoStats(categories, numgames)
  	games_played = currentStatLines.map{|player| player[:games_played]+1}

  	lastNGamesStatLines=lastNGamesStatLines.zip(games_played).map{|statLine,games| statLine.map{|stat| (stat.to_f*81/games)}}

  	min = lastNGamesStatLines.transpose.map{|column| column.min}
  	max = lastNGamesStatLines.transpose.map{|column| column.max}

  	adjustedStatLines = lastNGamesStatLines.map{|playerStats| playerStats.zip(min,max)}.map{|row|row.map{|stat,minStat,maxStat| ((stat.to_f-minStat)/(maxStat-minStat)).round(2)}}
  	adjustedStatLines = adjustedStatLines.zip(currentStatLines).map{|playerStatLine,current| playerStatLine.push(playerStatLine.sum/(current[:games_played]+1))}
  	adjustedStatLines = reinsertNamesGames(adjustedStatLines, currentStatLines, numGames)
  	adjustedStatLines.sort_by!{|statLine| -statLine[statLine.length-1]}
  end

end

app/controllers/cgame_controller.rb
class CgameController < ApplicationController
	@stats
	def index
		@categories=["name", "player_id", "games_played"]
		weights=[]
		@goals=false
		if params[:goals]
			@goals=true
			@categories.push("goals")
			weights.push(params[:goals_weight].to_f)
		end
		@assists=false
		if params[:assists]
			@assists=true
			@categories.push("assists")
			weights.push(params[:assists_weight].to_f)
		end
		@points=false
		if params[:points]
			@points=true
			@categories.push("points")
			weights.push(params[:points_weight].to_f)
		end
		@p_m=false
		if params[:'+-']
			@p_m=true
			@categories.push("plus_minus")
			weights.push(params[:'+-_weight'].to_f)
		end
		@pim=false
		if params[:pim]
			@pim=true
			@categories.push("pim")
			weights.push(params[:pim_weight].to_f)
		end
		@ppg=false
		if params[:ppg]
			@ppg=true
			@categories.push("ppg")
			weights.push(params[:ppg_weight].to_f)
		end
		@ppa=false
		if params[:ppa]
			@ppa=true
			@categories.push("ppa")
			weights.push(params[:ppa_weight].to_f)
		end
		@ppp=false
		if params[:ppp]
			@ppp=true
			@categories.push("ppp")
			weights.push(params[:ppp_weight].to_f)
		end
		@shg=false
		if params[:shg]
			@shg=true
			@categories.push("shg")
			weights.push(params[:shg_weight].to_f)
		end
		@sha=false
		if params[:sha]
			@sha=true
			@categories.push("sha")
			weights.push(params[:sha_weight].to_f)
		end
		@shp=false
		if params[:shp]
			@shp=true
			@categories.push("shp")
			weights.push(params[:shp_weight].to_f)
		end
		@gwg=false
		if params[:gwg]
			@gwg=true
			@categories.push("gwg")
			weights.push(params[:gwg_weight].to_f)
		end
		@otg=false
		if params[:otg]
			@otg=true
			@categories.push("otg")
			weights.push(params[:otg_weight].to_f)
		end
		@shots=false
		if params[:shots]
			@shots=true
			@categories.push("shots")
			weights.push(params[:shots_weight].to_f)
		end
		@toi=false
		if params[:toi]
			@toi=true
			@categories.push("toi")
			weights.push(params[:toi_weight].to_f)
		end
		@shifts=false
		if params[:shifts]
			@shifts=true
			@categories.push("shifts")
			weights.push(params[:shifts_weight].to_f)
		end
		@hits=false
		if params[:hits]
			@hits=true
			@categories.push("hits")
			weights.push(params[:hits_weight].to_f)
		end
		@blocks=false
		if params[:blocks]
			@blocks=true
			@categories.push("blocks")
			weights.push(params[:blocks_weight].to_f)
		end
		@mss=false
		if params[:mss]
			@mss=true
			@categories.push("mss")
			weights.push(params[:mss_weight].to_f)
		end
		@gva=false
		if params[:gva]
			@gva=true
			@categories.push("gva")
			weights.push(params[:gva_weight].to_f)
		end
		@tka=false
		if params[:tka]
			@tka=true
			@categories.push("tka")
			weights.push(params[:tka_weight].to_f)
		end
		@fo=false
		if params[:fo]
			@fo=true
			@categories.push("fo")
			weights.push(params[:fo_weight].to_f)
		end
		@fow=false
		if params[:fow]
			@fow=true
			@categories.push("fow")
			weights.push(params[:fow_weight].to_f)
		end
		@fol=false
		if params[:fol]
			@fol=true
			@categories.push("fol")
			weights.push(params[:fol_weight].to_f)
		end
		@numGames=params[:last_n_games]
		if @numGames == "" || @numGames== nil
			@numGames=100
		end
		@num_cats=@categories.length
		@categories= @categories.join(", ")
		weights.map!{|w| w==0 ? w=1 : w}
		@stats=Cgame.getTotal(@categories,@numGames.to_i, weights)
	end
end

app/helpers/cgame_helper.rb
module CgameHelper
end

app/views/cgame/index.html.erb
<%=form_tag stats_path, :method => 'get' do%>
<p>
<%= check_box_tag "goals", "goals", value="#{params[:goals]}"%>
<%=label_tag :goals%>
<%= number_field_tag :goals_weight , params[:goals_weight], step: :any%>

<%= check_box_tag "assists", "assists"%>
<%=label_tag :assists%>
<%= number_field_tag :assists_weight , params[:assists_weight]%>

<%= check_box_tag "points", "points"%>
<%=label_tag :points%>
<%= number_field_tag :points_weight , params[:points]%>

<%= check_box_tag "+-", "+-"%>
<%=label_tag :'+-'%>
<%= number_field_tag :'+-_weight' , params[:'+-_weight']%>

<%= check_box_tag "ppg", "ppg"%>
<%=label_tag :ppg%>
<%= number_field_tag :ppg_weight , params[:ppg_weight]%>

<%= check_box_tag "ppa", "ppa"%>
<%=label_tag :ppa%>
<%= number_field_tag :ppa_weight , params[:ppa_weight]%>

<%= check_box_tag "ppp", "ppp"%>
<%=label_tag :ppp%>
<%= number_field_tag :ppp_weight , params[:ppp_weight]%>

<%= check_box_tag "shg", "shg"%>
<%=label_tag :shg%>
<%= number_field_tag :shg_weight , params[:shg_weight]%>

<%= check_box_tag "shp", "shp"%>
<%=label_tag :shp%>
<%= number_field_tag :shp_weight , params[:shp_weight]%>

<%= check_box_tag "gwg", "gwg"%>
<%=label_tag :gwg%>
<%= number_field_tag :gwg_weight , params[:gwg_weight]%>

<%= check_box_tag "otg", "otg"%>
<%=label_tag :otg%>
<%= number_field_tag :otg_weight , params[:otg_weight]%>

<%= check_box_tag "shots", "shots"%>
<%=label_tag :shots%>
<%= number_field_tag :shots_weight , params[:shots_weight]%>

<%= check_box_tag "toi", "toi"%>
<%=label_tag :toi%>
<%= number_field_tag :toi_weight , params[:toi_weight]%>

<%= check_box_tag "shifts", "shifts"%>
<%=label_tag :shifts%>
<%= number_field_tag :shifts_weight , params[:shifts_weight]%>

<%= check_box_tag "hits", "hits"%>
<%=label_tag :hits%>
<%= number_field_tag :hits_weight , params[:hits_weight]%>

<%= check_box_tag "blocks", "blocks"%>
<%=label_tag :blocks%>
<%= number_field_tag :blocks_weight , params[:blocks_weight]%>

<%= check_box_tag "mss", "mss"%>
<%=label_tag :mss%>
<%= number_field_tag :mss_weight , params[:mss_weight]%>

<%= check_box_tag "gva", "gva"%>
<%=label_tag :gva%>
<%= number_field_tag :gva_weight , params[:gva_weight]%>

<%= check_box_tag "tka", "tka"%>
<%=label_tag :tka%>
<%= number_field_tag :tka_weight , params[:tka_weight]%>

<%= check_box_tag "fo", "fo"%>
<%=label_tag :fo%>
<%= number_field_tag :fo_weight , params[:fo_weight]%>

<%= check_box_tag "fow", "fow"%>
<%=label_tag :fow%>
<%= number_field_tag :fow_weight , params[:fow_weight]%>

<%= check_box_tag "fol", "fol"%>
<%=label_tag :fol%>
<%= number_field_tag :fol_weight , params[:fol_weight]%>

<%= check_box_tag "pim", "pim"%>
<%=label_tag :pim%>
<%= number_field_tag :pim_weight , params[:pim_weight]%>

<%= check_box_tag "sha", "sha"%>
<%=label_tag :sha%>
<%= number_field_tag :sha_weight , params[:sha_weight]%>

<%=label_tag :last_n_games%>
<%=number_field_tag :last_n_games, params[:last_n_games]%>
<%= submit_tag "search", :name=>nil %>



</p>
<%end%>

<table id="myTable" class="tablesorter tablesorter-blue">
	<thead>
	<tr>
		<th><span>Rank</span></th>
		<th>Name</th>
		<th>Games</th>
		<% if @goals %>
			<th>G</th>
		<%end%>

		<%if @assists %>
			<th>A</th>
		<%end%>

		<%if @points %>
			<th>P</th>
		<%end%>

		<%if @p_m %>
			<th>+-</th>
		<%end%>

		<%if @pim %>
			<th>PIM</th>
		<%end%>

		<%if @ppg%>
			<th>PPG</th>
		<%end%>

		<%if @ppa %>
			<th>PPA</th>
		<%end%>

		<%if @ppp %>
			<th>PPP</th>
		<%end%>

		<%if @shg %>
			<th>SHG</th>
		<%end%>

		<%if @sha %>
			<th>SHA</th>
		<%end%>

		<%if @shp %>
			<th>SHP</th>
		<%end%>

		<%if @gwg %>
			<th>GWG</th>
		<%end%>

		<%if @otg %>
			<th>OTG</th>
		<%end%>

		<%if @shots %>
			<th>S</th>
		<%end%>

		<%if @toi %>
			<th>TOI</th>
		<%end%>

		<%if @shifts %>
			<th>Shifts</th>
		<%end%>

		<%if @hits %>
			<th>Hits</th>
		<%end%>

		<%if @blocks %>
			<th>Blocks</th>
		<%end%>

		<%if @mss %>
			<th>MSS</th>
		<%end%>

		<%if @gva %>
			<th>GVA</th>
		<%end%>

		<%if @tka %>
			<th>TKA</th>
		<%end%>

		<%if @fo %>
			<th>FO</th>
		<%end%>

		<%if @fow %>
			<th>FOW</th>
		<%end%>

		<%if @fol %>
			<th>FOL</th>
		<%end%>
		<th> Score</th>
	</tr>
	</thead>

	<% (@stats.length).times do |i| %>
	<tr>
		<td><%=link_to "#{i}", player_path(:id=>i)%>
		<%(@num_cats-1).times do |j|%>

			<td><%=@stats[i][j] %></td>
		<%end%>
		<td><%=@stats[i][@num_cats-1] %></td>
	</tr>
	<% end %>
</table>